const laywers = [
    {
        name: "Rajesh",
        tag: "Criminal Lawyer",
        age: "30",
        countPastCases: "10",
        experience: "5 years",
        countWonCases: "7",
        description: "I am a criminal lawyer with 5 years of experience. I have won 7 cases in the past. I have handled 10 cases in the past.",
        country: "India",
        state: "Karnataka",
        city: "Bangalore",
        takesProBono: true,
        img: "https://www.w3schools.com/howto/img_avatar.png",   
        requests:[
            {
                userName: "Heena",
                userImg: "https://www.w3schools.com/howto/img_avatar.png",
                status: "pending",
                chatRequest: true,
                hireRequest: false,
            },
            {
                userName: "Meena",
                userImg: "https://www.w3schools.com/howto/img_avatar.png",
                status: "pending",
                chatRequest: true,
                hireRequest: true,
            },
            {
                userName: "Teena",
                userImg: "https://www.w3schools.com/howto/img_avatar.png",
                status: "pending",
                chatRequest: false,
                hireRequest: true,
            }
        ]
    },
    {
        name: "Ramesh",
        tag: "Criminal Lawyer",
        age: "30",
        countPastCases: "10",
        experience: "5 years",
        countWonCases: "7",
        description: "I am a criminal lawyer with 5 years of experience. I have won 7 cases in the past. I have handled 10 cases in the past.",
        country: "India",
        state: "Karnataka",
        city: "Bangalore",
        takesProBono: false,
        img: "https://www.w3schools.com/howto/img_avatar.png",
    },
    {
        name: "Rajesh",
        tag: "Criminal Lawyer",
        age: "30",
        countPastCases: "10",
        experience: "5 years",
        countWonCases: "7",
        description: "I am a criminal lawyer with 5 years of experience. I have won 7 cases in the past. I have handled 10 cases in the past.",
        country: "India",
        state: "Karnataka",
        city: "Bangalore",
        takesProBono: true,
        img: "https://www.w3schools.com/howto/img_avatar.png",
    },
    {
        name: "Rajesh",
        tag: "Criminal Lawyer",
        age: "30",
        countPastCases: "10",
        experience: "5 years",
        countWonCases: "7",
        description: "I am a criminal lawyer with 5 years of experience. I have won 7 cases in the past. I have handled 10 cases in the past.",
        country: "India",
        state: "Karnataka",
        city: "Bangalore",
        takesProBono: false,
        img: "https://www.w3schools.com/howto/img_avatar.png",
    },

]

export default laywers;